# Build cross-platform wheels for Windows, macOS, and Linux using cibuildwheel.
# Handles manylinux compatibility and cross-compilation automatically.

name: Build tiny3D Wheels (cross-platform)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (host interp for cibuildwheel driver)
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels (cp39 & cp312)
        run: python -m cibuildwheel python --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_BUILD: "cp39-* cp312-*"
          CIBW_SKIP: "pp* *-musllinux*"  # Skip PyPy and musl builds
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_BEFORE_BUILD_LINUX: >
            dnf install -y --nogpgcheck cmake ninja-build gcc-c++ python3-devel &&
            pip install cmake ninja &&
            rm -f /project/CMakeCache.txt /project/cmake_install.cmake
          CIBW_BEFORE_BUILD_WINDOWS: >
            pip install cmake ninja mkl-devel delvewheel
          CIBW_BEFORE_BUILD_MACOS: >
            pip install cmake ninja
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD_FRONTEND: "build"
          # Enable debug output to see what's happening with extension building/copying
          CIBW_ENVIRONMENT: "TINY3D_VERBOSE=1"
          # Enable OpenMP on Windows with Intel runtime (more reliable)
          CIBW_ENVIRONMENT_WINDOWS: "TINY3D_VERBOSE=1 TINY3D_WITH_OPENMP_WINDOWS=1 CMAKE_ARGS=-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"

      - name: Test wheel install (cp39)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install --find-links wheelhouse tiny3d
          python -c "import tiny3d; print('tiny3d version:', tiny3d.__version__, 'native:', getattr(tiny3d,'_HAVE_NATIVE','undef'), 'py:', __import__('sys').version.split()[0])"
      - name: Test wheel install (cp312)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install --find-links wheelhouse tiny3d
          python -c "import tiny3d; print('tiny3d version:', tiny3d.__version__, 'native:', getattr(tiny3d,'_HAVE_NATIVE','undef'), 'py:', __import__('sys').version.split()[0])"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

# To publish to PyPI, uncomment and configure the following step:
#      - name: Publish to PyPI
#        uses: pypa/gh-action-pypi-publish@v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}


